[theme]
primaryColor = "#0d6efd"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
address = "0.0.0.0"
port = 8000
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"
